repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
      exclude: ^.*\b(alembic)\b.*$

-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
      exclude: ^.*\b(alembic)\b.*$
      args: [ --config, pyproject.toml ]

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      exclude: ^.*\b(alembic)\b.*$
      args: [--config, setup.cfg]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        name: admin-mypy
        files: ^admin/
        exclude: ^.*\b(alembic)\b.*$
        args: [--config, setup.cfg]
      - id: mypy
        name: auth-mypy
        files: ^auth/
        exclude: ^.*\b(alembic)\b.*$
        args: [--config, setup.cfg]
      - id: mypy
        name: common-mypy
        files: ^common/
        exclude: ^.*\b(alembic)\b.*$
        args: [--config, setup.cfg]
      - id: mypy
        name: core-mypy
        files: ^core/
        exclude: ^.*\b(alembic)\b.*$
        args: [--config, setup.cfg]
      - id: mypy
        name: uploader-mypy
        files: ^uploader/
        exclude: ^.*\b(alembic)\b.*$
        args: [--config, setup.cfg]
      - id: mypy
        name: users-mypy
        files: ^users/
        exclude: ^.*\b(alembic)\b.*$
        args: [--config, setup.cfg]
