repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    - id: isort
      exclude: ^.*\b(alembic)\b.*$

-   repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
    - id: black
      exclude: ^.*\b(alembic)\b.*$
      args: [ --config, pyproject.toml ]

#-   repo: https://github.com/PyCQA/flake8
#    rev: 4.0.1
#    hooks:
#    - id: flake8
#      exclude: ^.*\b(alembic)\b.*$
#      args: [--config, setup.cfg]
#
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.931
#    hooks:
#      - id: mypy
#        exclude: ^tests/
#        args: [--config, setup.cfg]
